# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

- name: log_incident
  config:
    handlers:
      #- http://127.0.0.1:8080/
      - file:///opt/dionaea/var/log/dionaea/dionaea-incident.json
