name: klack-cloud

include:
  - ./compose/traefik.yml
  - ./compose/fail2ban.yml
  - ./compose/grafana.yml
  - ./compose/watchtower.yml
  - ./compose/dionaea.yml
  - ./compose/whoami.yml
  - ./compose/sftpgo.yml
  - ./compose/photoprism.yml
  - ./compose/plex.yml
  - ./compose/qbittorrent-wireguard.yml
  - ./compose/radarr.yml
  - ./compose/sonarr.yml
  - ./compose/jackett.yml
  - ./compose/unpackerr.yml

networks:
  klack:
    external: true