name: klack-cloud

include:
  - ./compose/traefik.yml
  - ./compose/fail2ban.yml
  - ./compose/grafana.yml
  - ./compose/watchtower.yml
  - ./compose/dionaea.yml
  - ./compose/prometheus.yml
  - ./compose/cowrie.yml
  - ./compose/duplicati.yml
  - ./compose/sftpgo.yml
  - ./compose/plex.yml
  - ./compose/qbittorrent-wireguard.yml
  - ./compose/radarr.yml
  - ./compose/sonarr.yml
  - ./compose/jackett.yml
  - ./compose/unpackerr.yml
  - ./compose/nginx.yml
  - ./compose/immich.yml
  - ./compose/radicale.yml  
  # - ./compose/whoami.yml # Used to diagnose middleware

networks:
  klack:

  honey:
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE} # Replace 'eno1' with your actual network interface name
    ipam:
      config:
        - subnet: ${HONEYPOT_SUBNET} # Replace with your network's subnet
          gateway: ${HONEYPOT_GATEWAY} # Replace with your network's gateway
