tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/server.crt
        keyFile: /etc/traefik/certs/server.key

http:
  routers:
    node-exporter:
      rule: "Host(`node-exp.klack.internal`)"
      service: node-exporter
      entryPoints:
        - internal
      middlewares:
        - traefik-auth
  
  middlewares:
    traefik-auth:
      basicAuth:
        usersFile: "/htpasswd"
  
  services:
    node-exporter:
      loadBalancer:
        servers:
          - url: "http://192.168.20.7:9100"  # Adjust as needed
