providers:
  file:
    directory: /config/dynamic/
  docker:
    exposedByDefault: false

accessLog:
  filePath: /logs/traefik-access.log
  addInternals: true
  fields:
    names:
      StartUTC: drop #Fixes incorrect timezone in access log

api: true

metrics:
  prometheus:
    entryPoint: internal

entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: web-secure
          scheme: https

  web-secure:
    address: ":443"
    asdefault: true
    http:
      tls: true

  grafana:
    address: ":3000"
    http:
      tls: true

  duplicati:
    address: ":8200"
    http:
      tls: true

  qbittorrent:
    address: ":8080"
    http:
      tls: true

  sftpgo:
    address: ":8081"
    http:
      tls: true

  traefik:
    address: ":8082"
    http:
      tls: true

  sonarr:
    address: ":8989"
    http:
      tls: true

  jackett:
    address: ":9117"
    http:
      tls: true

  radarr:
    address: ":7878"
    http:
      tls: true

  plex:
    address: ":32400"
    http:
      tls: true

  immich:
    address: ":2283"
    http:
      tls: true

  internal:
    address: ":4443"
    http:
      tls: true

  metrics:
    address: ":9101"
    http:
      tls: true

certificatesResolvers:
  myresolver:
    acme:
      email: admin@suntrustmail.com
      storage: /acme/acme.json
      tlsChallenge: {}
