volumes:
  cowrie:

services:
  cowrie:
    image: cowrie/cowrie
    environment:
      - "COWRIE_TELNET_ENABLED=yes"
      - "COWRIE_TELNET_LISTEN_ENDPOINTS=tcp:23:interface=0.0.0.0"
      - "COWRIE_SSH_LISTEN_ENDPOINTS=tcp:22:interface=0.0.0.0"
    volumes:
      - /var/log/cowrie:/cowrie/cowrie-git/var/log/cowrie
      - cowrie:/cowrie/cowrie-git/
    networks:
      honey:
        ipv4_address: ${HONEYPOTSSH_IPV4}
    restart: always