volumes:
  cowrie:
  cowrie-downloads: #Files downloaded by an attacker are stored here

services:
  cowrie:
    image: cowrie/cowrie
    environment:
      - "COWRIE_TELNET_ENABLED=yes"
      - "COWRIE_TELNET_LISTEN_ENDPOINTS=tcp:23:interface=0.0.0.0"
      - "COWRIE_SSH_LISTEN_ENDPOINTS=tcp:22:interface=0.0.0.0"
    volumes:
      - cowrie:/cowrie/cowrie-git/
      - cowrie-downloads:/cowrie/cowrie-git/var/lib/cowrie/downloads/
      - /var/log/cowrie:/cowrie/cowrie-git/var/log/cowrie
    networks:
      honey:
        ipv4_address: ${HONEYPOTSSH_IPV4}
    restart: always