services:
  cowrie:
    image: cowrie/cowrie
    user: 1000:1000
    environment:
      - "COWRIE_TELNET_ENABLED=yes"
      - "COWRIE_TELNET_LISTEN_ENDPOINTS=tcp:23:interface=0.0.0.0"
      - "COWRIE_SSH_LISTEN_ENDPOINTS=tcp:22:interface=0.0.0.0"
    volumes:
      - /var/log/cowrie:/cowrie/cowrie-git/var/log/cowrie
    ports:
      - "2222:22"
    # networks:
    #   honey:
    #     ipv4_address: ${HONEYPOTSSH_IPV4}
