volumes:
  duplicati:

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Denver
      - CLI_ARGS= --log-file=/var/log/duplicati/duplicati.log
    volumes:
      - duplicati:/config
      - /var/log/duplicati:/var/log/duplicati
      - ${DIR_BACKUPS}:/backups
      - ${DIR_JOPLIN}:/source/joplin:ro
      - ${DIR_PHOTOS}:/source/photos:ro
      - ${DIR_SFTPGOROOT}:/source/sftpgoroot:ro
      - ${DIR_KLACKTV}:/source/klack.tv:ro      
    # ports:
    #   - 8200:8200
    networks:
      klack:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.duplicati.entrypoints=internal"
      - "traefik.http.routers.duplicati.service=duplicati"
      - "traefik.http.routers.duplicati.middlewares=traefik-auth@file"      
      - "traefik.http.services.duplicati.loadBalancer.server.port=8200"
      - "stack=klack.cloud"      
    restart: always
