services:
  fail2ban:
    image: crazymax/fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "../config/fail2ban:/data"
      - /var/log/traefik/:/logs/traefik/
    environment:
      TZ: ${TZ} # Set the timezone
      F2B_LOG_LEVEL: INFO # Set log level to INFO
      F2B_DB_PURGE_AGE: 1d # Set database purge age to 1 day
    network_mode: "host"
    labels:
      - "stack=${EXTERNAL_DOMAIN}"
    restart: always
