volumes:
  grafana-storage:

services:
  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ../config/loki:/etc/loki
    networks:
      - klack
    labels:
      - "stack=loggers"
    restart: always
    # ports:
    #   - "3100:3100"

  promtail:
    image: grafana/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ../config/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/traefik:/logs/traefik
      - /var/log/sonarr:/logs/sonarr
      - /var/log/radarr:/logs/radarr
      - /var/log/dionaea:/logs/dionaea
      - /var/log/cowrie:/logs/cowrie
    networks:
      - klack
    labels:
      - "stack=loggers"
    depends_on:
      loki:
        condition: service_started
    restart: always
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs

  grafana:
    image: grafana/grafana
    user: 1000:1000 # Required
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: ${GF_SMTP_HOST}
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS}
      GF_SMTP_USER: ${GF_SMTP_USER}
      GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD}
      GF_SERVER_ROOT_URL: https://grafana.${INTERNAL_DOMAIN}:4443
    networks:
      - klack
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=internal"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadBalancer.server.port=3000"
      - "stack=loggers"
    depends_on:
      loki:
        condition: service_started
    restart: always
