volumes:
  grafana-storage:

services:
  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ../config/loki:/etc/loki
    environment:
      TZ: ${TZ}
    networks:
      - klack
    labels:
      - "stack=loggers"
    restart: always
    # ports:
    #   - "3100:3100"

  promtail:
    image: grafana/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ../config/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/traefik:/logs/traefik
      - /var/log/sonarr:/logs/sonarr
      - /var/log/radarr:/logs/radarr
      - /var/log/dionaea:/logs/dionaea
      - /var/log/cowrie:/logs/cowrie
      - /var/log/duplicati:/logs/duplicati
      - /var/log/plex:/logs/plex
    environment:
      TZ: ${TZ}
    networks:
      - klack
    labels:
      - "stack=loggers"
    depends_on:
      loki:
        condition: service_started
    restart: always
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs

  grafana:
    image: grafana/grafana
    user: 1000:1000 # Required
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../config/grafana/provisioning:/etc/grafana/provisioning
      - ../config/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      TZ: ${TZ}
      GF_SECURITY_ADMIN_USER: ${CLOUD_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${CLOUD_PASS}      
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: ${GF_SMTP_HOST}
      GF_SMTP_FROM_ADDRESS: ${GF_SMTP_FROM_ADDRESS}
      GF_SMTP_USER: ${GF_SMTP_USER}
      GF_SMTP_PASSWORD: ${GF_SMTP_PASSWORD}
      GF_SERVER_ROOT_URL: https://${HOST_IP}:3000
    networks:
      - klack
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/`)"
      - "traefik.http.routers.grafana.entrypoints=grafana"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadBalancer.server.port=3000"
      - "stack=loggers"
    depends_on:
      loki:
        condition: service_started
    restart: always
