volumes:
  jackett:

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    logging:
      driver: none
    profiles:
      - downloaders
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
      - AUTO_UPDATE=false # We use watchtower instead
      - RUN_OPTS=
    volumes:
      - jackett:/config
      - ../config/jackett/ServerConfig.json:/config/Jackett/ServerConfig.json
      - /dev/null:/config/Jackett/log.txt # Suppress log file
      - /dev/null:/config/Jackett/updater.txt # No way to expose this properly outside the container so it can be rotated. (the container is unable to write to the file)
      - .${DIR_CLOUD_ROOT}/${CLOUD_USER}/Downloads:/downloads
    
    network_mode: service:qbittorrent-wireguard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.jackett.entrypoints=internal"
      - "traefik.http.routers.jackett.service=jackett"
      - "traefik.http.routers.jackett.middlewares=traefik-auth@file"
      - "traefik.http.services.jackett.loadBalancer.server.port=9117"
    restart: unless-stopped
    # ports:
    #   - 9117:9117
