volumes:
  jackett:

services:
  jackett:
    image: lscr.io/linuxserver/jackett
    profiles:
      - downloaders
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true # optional
      - RUN_OPTS= # optional
    volumes:
      - jackett:/config
      - ../data/klack.tv/downloads:/downloads
    network_mode: service:qbittorrent-wireguard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.jackett.entrypoints=internal"
      - "traefik.http.routers.jackett.service=jackett"
      - "traefik.http.routers.jackett.middlewares=traefik-auth@file"
      - "traefik.http.services.jackett.loadBalancer.server.port=9117"
    restart: always
    # ports:
    #   - 9117:9117
