volumes:
  prometheus-storage:

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ../config/prometheus/entrypoint.sh:/entrypoint.sh # Add the entrypoint script
      - ../config/prometheus/prometheus.yml.template:/etc/prometheus/prometheus.yml.template
      - prometheus-storage:/prometheus
    environment:
      TZ: ${TZ}
      NODE_EXPORTER_TARGET: "${HOST_IP}:9101"
      TRAEFIK_TARGET: "${HOST_IP}:4443"
      CLOUD_USER: ${CLOUD_USER}
      CLOUD_PASS: ${CLOUD_PASS}
    entrypoint: ["/entrypoint.sh"]
    # ports:
    #   - "9090:9090"
    networks:
      - klack
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/`)"
      - "traefik.http.routers.prometheus.entrypoints=internal"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.routers.prometheus.middlewares=traefik-auth@file"
      - "traefik.http.services.prometheus.loadBalancer.server.port=9090"
      - "stack=loggers"
    restart: always
