volumes:
  prometheus-storage:

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ../config/prometheus/entrypoint.sh:/entrypoint.sh # Add the entrypoint script
      - ../config/prometheus/prometheus.yml.template:/etc/prometheus/prometheus.yml.template
      - ../config/traefik/certs/ca.crt:/etc/prometheus/ca.crt
      - prometheus-storage:/prometheus
    environment:
      TZ: ${TZ}
      NODE_EXPORTER_TARGET: "node-exp.${INTERNAL_DOMAIN}:9101"
      TRAEFIK_TARGET: "${HOST_IP}:4443"
      NODE_EXPORTER_USER: ${BASIC_AUTH_USER}
      NODE_EXPORTER_PASS: ${BASIC_AUTH_PASS}
    entrypoint: ["/entrypoint.sh"]
    # ports:
    #   - "9090:9090"
    networks:
      - klack
    extra_hosts:
      - "node-exp.klack.internal:${HOST_IP}" # Use host IP
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.prometheus.entrypoints=internal"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.routers.prometheus.middlewares=traefik-auth@file"
      - "traefik.http.services.prometheus.loadBalancer.server.port=9090"
      - "stack=loggers"
    restart: always
