services:
  radicale:
    image: tomsquest/docker-radicale
    # ports:
    #   - 5232:5232
    user: "1000:1000"
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    profiles:
      - apps
    volumes:
      - $DIR_CLOUD_ROOT/$CLOUD_USER/Planner:/data
      - ../config/radicale:/config
      - ../config/traefik/htpasswd:/config/users
    networks:
      - klack
    environment:
      - TAKE_FILE_OWNERSHIP=false
      - UID=1000
      - GID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radicale.rule=PathPrefix(`/planner/`)"
      - "traefik.http.routers.radicale.entrypoints=web-secure"
      - "traefik.http.routers.radicale.middlewares=radicaleh,radicales"
      - "traefik.http.middlewares.radicaleh.headers.customrequestheaders.X-Script-Name=/planner"
      - "traefik.http.middlewares.radicales.stripprefix.prefixes=/planner/"
      - "stack=klack.cloud"
