volumes:
  sftpgo:

services:
  sftpgo:
    image: drakkan/sftpgo
    profiles:
      - apps
    volumes:
      - ../config/sftpgo/sftpgo.json:/etc/sftpgo/sftpgo.json
      - sftpgo:/var/lib/sftpgo
      - .${DIR_CLOUD_ROOT}:/srv/sftpgo/data
    environment:
      TZ: ${TZ}
      SFTPGO_DEFAULT_ADMIN_USERNAME: ${CLOUD_USER}
      SFTPGO_DEFAULT_ADMIN_PASSWORD: ${CLOUD_PASS}
    networks:
      klack:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sftpgo-ui.rule=Host(`sftpgo.${INTERNAL_DOMAIN}`)"
      - "traefik.http.routers.sftpgo-ui.service=sftpgo-ui"
      - "traefik.http.routers.sftpgo-ui.entrypoints=internal"
      - "traefik.http.routers.sftpgo-ui.tls.certresolver=myresolver"
      - "traefik.http.services.sftpgo-ui.loadBalancer.server.port=8080"
      - "traefik.http.routers.sftpgo.rule=Host(`${EXTERNAL_DOMAIN}`) && PathPrefix(`/dav`)"
      - "traefik.http.routers.sftpgo.service=sftpgo"
      - "traefik.http.routers.sftpgo.tls.certresolver=myresolver"
      - "traefik.http.services.sftpgo.loadBalancer.server.port=80"
      - "stack=klack.cloud"
    restart: unless-stopped
