services:
  sftpgo:
    image: drakkan/sftpgo
    profiles:
      - apps
    volumes:
      - ../config/sftpgo/homeuser:/var/lib/sftpgo
      - ../config/sftpgo/sftpgo.json:/etc/sftpgo/sftpgo.json
      - ${DIR_SFTPGOROOT}:/srv/sftpgo
      - ${DIR_JOPLIN}:/joplin
      - ${DIR_PHOTOS}../data/photos:/photos
    networks:
      frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sftpgo-ui.rule=Host(`sftpgo.klack.internal`)"
      - "traefik.http.routers.sftpgo-ui.service=sftpgo-ui"
      - "traefik.http.routers.sftpgo-ui.entrypoints=internal"
      - "traefik.http.routers.sftpgo-ui.tls.certResolver=myresolver"
      - "traefik.http.services.sftpgo-ui.loadBalancer.server.port=8080"
      - "traefik.http.routers.sftpgo.rule=Host(`klack.cloud`) && PathPrefix(`/dav`)"
      - "traefik.http.routers.sftpgo.service=sftpgo"
      - "traefik.http.routers.sftpgo.tls.certResolver=myresolver"
      - "traefik.http.services.sftpgo.loadBalancer.server.port=80"
      - "stack=klack.cloud"
    restart: always
