volumes:
  acme:

services:
  traefik:
    image: traefik
    environment:
      TZ: ${TZ}
      HOST_IP: ${HOST_IP}
      INTERNAL_DOMAIN: ${INTERNAL_DOMAIN}
    volumes:
      - ../config/traefik/entrypoint.sh:/entrypoint.sh
      - ../config/traefik/dynamic:/config/dynamic
      - ../config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ../config/traefik/htpasswd:/htpasswd
      - ../config/traefik/certs/:/etc/traefik/certs/
      - /var/log/traefik/:/logs/
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/acme
    ports:
      - "443:443"
      - "32400:32400"
      - "4443:4443"
      - "2283:2283"
      - "9101:9101"
      - "8200:8200"
      - "3000:3000"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "9117:9117"      
      - "7878:7878"
      - "8989:8989"      
      - "9090:9090"
    networks:
      klack:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/`)"
      - "traefik.http.routers.api.entrypoints=traefik"
      - "traefik.http.routers.api.middlewares=traefik-auth@file"
      - "traefik.http.routers.api.service=api@internal"
      - "stack=klack.cloud"
    restart: always
