services:
  watchtower:
    image: containrrr/watchtower
    environment:
      TZ: ${TZ}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 7200 # checks for updates every two hours
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      frontend:
    labels:
      - "stack=klack.cloud"
    restart: always
