services:
  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    networks:
      klack:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${EXTERNAL_DOMAIN}`) && Path(`/whoami`)"
      - "traefik.http.routers.whoami.middlewares=traefik-auth@file"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "stack=klack.cloud"
