apiVersion: 1
groups:
    - orgId: 1
      name: 1m
      folder: CRITICAL
      interval: 1m
      rules:
        - uid: edwmrnaxbtla8b
          title: Low Root FS Freespace
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ddw4kf5ococ8wc
              model:
                datasource:
                    type: prometheus
                    uid: ddw4kf5ococ8wc
                editorMode: code
                expr: 100 * (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: rYdddlPWk
          panelId: 152
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: rYdddlPWk
            __panelId__: "152"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: edwq9w4u3kx6of
          title: Cowrie
          condition: C
          data:
            - refId: A
              queryType: range
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: fdw4k6iv40fswd
              model:
                datasource:
                    type: loki
                    uid: fdw4k6iv40fswd
                editorMode: code
                expr: count_over_time({filename="/logs/cowrie/cowrie.json"}[$__auto])
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: range
                refId: A
            - refId: B
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: adwq8sz89vaioa
          panelId: 2
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: adwq8sz89vaioa
            __panelId__: "2"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
        - uid: fdwqacr5416o0a
          title: Dionaea
          condition: C
          data:
            - refId: A
              queryType: range
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: fdw4k6iv40fswd
              model:
                datasource:
                    type: loki
                    uid: fdw4k6iv40fswd
                editorMode: code
                expr: count_over_time( {filename="/logs/dionaea/dionaea-incident.json"}[$__auto])
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: range
                refId: A
            - refId: B
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 86400
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: adwq8sz89vaioa
          panelId: 1
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: adwq8sz89vaioa
            __panelId__: "1"
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
